name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DONNA_CLI_USE_TRASH: "false"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy check
        run: cargo clippy -- -D warnings


  version-check:
    name: Version Check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check if version was updated
        run: |
          # Get current version
          CURRENT_VERSION=$(grep '^version =' Cargo.toml | head -1 | sed 's/.*= "//' | sed 's/".*//')
          
          # Check if tag already exists
          if git rev-parse "v${CURRENT_VERSION}" >/dev/null 2>&1; then
            echo "❌ Version ${CURRENT_VERSION} already exists as a tag!"
            echo "Please update the version in Cargo.toml before merging to main."
            exit 1
          else
            echo "✅ Version ${CURRENT_VERSION} is new!"
          fi